language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit -v

notifications:
    on_success: never
    on_failure: always
